# db config

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
    initialSize: 20
    minIdle: 10
    maxActive: 100
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 1000
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.laurdawn.website.dao

logging:
  config: classpath:log4j2-dev.yml

server:
  port: 8081
