# db config

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456
    initialSize: 20
    minIdle: 10
    maxActive: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.laurdawn.website.dao

server:
  port: 8080
