# db config

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://mariadb:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: laurdawn@ckm
    initialSize: 20
    minIdle: 10
    maxActive: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.laurdawn.website.dao
  
logging:
  config: classpath:log4j2-pro.yml
  
server:
  port: 8081