version: '3.5'
services:
  app:
    image: java:8-alpine
    restart: always
    ports:
      - 8091:8091
    working_dir: /usr/src/myapp
    volumes:
      - ./springboot_base.jar:/usr/src/myapp/springboot_base.jar
      #- /var/run/docker.sock:/var/run/docker.sock
    command: java -jar springboot_base.jar